sudo: required
language: python
python:
    - "2.7"
env:
    - CKANVERSION=2.6.3 POSTGISVERSION=2
    - CKANVERSION=2.7.0 POSTGISVERSION=2
services:
    - redis-server
    - postgresql
install:
    - bash bin/travis-build.bash
script: 
    - sh bin/travis-run.sh
after_success: coveralls
branches:
  only:
    - ngsiv2
